### ISSUE TITLE
I want to know how is the structure of the model: "person_detect_model_data.h"

### ISSUE THREAD

**Issue by msalexms** [trevorwslee/Arduino-DumbDisplay#151]
I am trying to convert this model into a .tflite, to see the shape and the structure of the model, but I get an error.
If somebody can tell me the structure of the model o how to transform it correctly please.
And also this model detect persons or faces?

Model: [https://github.com/trevorwslee/Arduino-DumbDisplay/blob/master/projects/esp32tensorflowlite/esp32cam_person/esp32cam_person.ino](url)

Thanks.

**Comment by trevorwslee** [comment]
You may want to take a look at my post

ESP32-CAM Person Detection Experiment With TensorFlow Lite -- https://www.instructables.com/ESP32-CAM-Person-Detection-Expreiment-With-TensorF/

to see if it can give you the info you want.

BTW, as far as I know, the DL model is supposed to detect person.

**Comment by msalexms** [comment]
Thanks!
